INSERT INTO advice (message, category, is_yes_or_no) VALUES ('Always give 100% at work: 12% Monday, 23% Tuesday, 40% Wednesday, 20% Thursday, 5% Friday.', 'work', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('Do not be afraid to step out of your comfort zone, new challenges bring new opportunities.', 'work', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('Remember, teamwork is key to a harmonious workplace.', 'work', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('Networking is not just about connecting people, it\'s about connecting people with people, people with ideas, and people with opportunities.', 'work', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('Do not check your email constantly; this is not a productive way to get the work done.', 'work', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('Study hard, but remember to take breaks; this boosts productivity.', 'school', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('Participation in class does not mean just showing up. Try to engage actively.', 'school', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('Organize your study space for better concentration and fewer distractions.', 'school', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('Never hesitate to ask for help, whether it\'s from a teacher or a classmate.', 'school', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('Prioritize your assignments by due date and the amount of time you estimate they\'ll take.', 'school', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('Always borrow money from a pessimist, they won’t expect it back.', 'funny', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('If life gives you lemons, squirt someone in the eye.', 'funny', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('Change is inevitable, except from a vending machine.', 'funny', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('If you think nobody cares if you\'re alive, try missing a couple of car payments.', 'funny', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('To steal ideas from one person is plagiarism; to steal from many is research.', 'funny', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('Follow your heart but take your brain with you.', 'general', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('The best time to plant a tree was 20 years ago. The second best time is now.', 'general', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('You miss 100% of the shots you don’t take.', 'general', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('Worrying is like paying a debt you don’t owe.', 'general', false);
INSERT INTO advice (message, category, is_yes_or_no) VALUES ('Always remember that you are unique, just like everyone else.', 'general', false);
